name: Godot CI
on:
  push:
    tags:
      - 'v*'

jobs:
  export-game:
    name: Export game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Wine
        id: wine_install
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
      - name: Export
        id: export
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1/Godot_v4.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1/Godot_v4.1-stable_export_templates.tpz
          relative_project_path: ./
          cache: true
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.${{ github.ref_name }}.windows
          path: ${{ steps.export.outputs.build_directory }}/Windows Desktop
      - name: Upload MacOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.${{ github.ref_name }}.mac
          path: ${{ steps.export.outputs.build_directory }}/macOS
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.${{ github.ref_name }}.linux
          path: ${{ steps.export.outputs.build_directory }}/LinuxX11
      - name: Upload Web artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.${{ github.ref_name }}.web
          path: ${{ steps.export.outputs.build_directory }}/Web

  itch-io-upload:
    name: Upload to Itch.io
    needs: export-game
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows, mac, linux, web]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.${{ github.ref_name }}.${{ matrix.platform }}
      - name: Butler Upload
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.platform }}
          ITCH_GAME: ${{ github.event.repository.name }}
          ITCH_USER: brawmario
          PACKAGE: .
          VERSION: ${{ github.ref_name }}

  pages-deploy:
    name: Deploy to GitHub Pages
    needs: export-game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Artifact (web)
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.${{ github.ref_name }}.web
          path: export/web
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: export/web